import type { Food } from "./food.type";

export const dummyFoods: Food[] = [
  {
    id: 1,
    name: "Dummy Curry",
    cuisine: "Japanese",
    dietaryTags: ["vegan"],
    difficulty: "easy",
    nutrition: { calories: 300, protein: 10, carbs: 50, fat: 5 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 2,
    name: "Dummy Salad",
    cuisine: "Western",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 120, protein: 3, carbs: 20, fat: 4 },
    servings: 1,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 3,
    name: "Dummy Hamburger",
    cuisine: "American",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 550, protein: 25, carbs: 40, fat: 30 },
    servings: 1,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 4,
    name: "Dummy Sushi",
    cuisine: "Japanese",
    dietaryTags: ["seafood"],
    difficulty: "hard",
    nutrition: { calories: 350, protein: 14, carbs: 60, fat: 5 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 5,
    name: "Dummy Pizza",
    cuisine: "Italian",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 400, protein: 15, carbs: 50, fat: 18 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 6,
    name: "Dummy Pad Thai",
    cuisine: "Thai",
    dietaryTags: ["seafood"],
    difficulty: "medium",
    nutrition: { calories: 430, protein: 16, carbs: 65, fat: 12 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 7,
    name: "Dummy Tacos",
    cuisine: "Mexican",
    dietaryTags: ["meat"],
    difficulty: "easy",
    nutrition: { calories: 320, protein: 12, carbs: 35, fat: 12 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 8,
    name: "Dummy Pho",
    cuisine: "Vietnamese",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 280, protein: 14, carbs: 40, fat: 6 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 9,
    name: "Dummy Bibimbap",
    cuisine: "Korean",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 370, protein: 9, carbs: 60, fat: 10 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 10,
    name: "Dummy Falafel",
    cuisine: "Middle Eastern",
    dietaryTags: ["vegan"],
    difficulty: "easy",
    nutrition: { calories: 245, protein: 7, carbs: 25, fat: 13 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 11,
    name: "Dummy Paella",
    cuisine: "Spanish",
    dietaryTags: ["seafood"],
    difficulty: "hard",
    nutrition: { calories: 500, protein: 18, carbs: 70, fat: 13 },
    servings: 4,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 12,
    name: "Dummy Goulash",
    cuisine: "Hungarian",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 380, protein: 18, carbs: 28, fat: 17 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 13,
    name: "Dummy Borscht",
    cuisine: "Russian",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 110, protein: 3, carbs: 22, fat: 2 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 14,
    name: "Dummy Moussaka",
    cuisine: "Greek",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 410, protein: 19, carbs: 38, fat: 19 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 15,
    name: "Dummy Ratatouille",
    cuisine: "French",
    dietaryTags: ["vegan"],
    difficulty: "easy",
    nutrition: { calories: 95, protein: 2, carbs: 17, fat: 4 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 16,
    name: "Dummy Tom Yum Soup",
    cuisine: "Thai",
    dietaryTags: ["seafood"],
    difficulty: "easy",
    nutrition: { calories: 120, protein: 6, carbs: 10, fat: 6 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 17,
    name: "Dummy Jollof Rice",
    cuisine: "West African",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 350, protein: 6, carbs: 70, fat: 6 },
    servings: 4,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 18,
    name: "Dummy Chili Con Carne",
    cuisine: "Tex-Mex",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 410, protein: 21, carbs: 45, fat: 16 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 19,
    name: "Dummy Shepherd's Pie",
    cuisine: "British",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 330, protein: 14, carbs: 35, fat: 13 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 20,
    name: "Dummy Laksa",
    cuisine: "Malaysian",
    dietaryTags: ["seafood"],
    difficulty: "medium",
    nutrition: { calories: 370, protein: 11, carbs: 50, fat: 14 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 21,
    name: "Dummy Butter Chicken",
    cuisine: "Indian",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 540, protein: 23, carbs: 30, fat: 33 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 22,
    name: "Dummy Shakshuka",
    cuisine: "Middle Eastern",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 210, protein: 8, carbs: 20, fat: 11 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 23,
    name: "Dummy Ceviche",
    cuisine: "Peruvian",
    dietaryTags: ["seafood"],
    difficulty: "medium",
    nutrition: { calories: 120, protein: 13, carbs: 9, fat: 4 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 24,
    name: "Dummy Doro Wat",
    cuisine: "Ethiopian",
    dietaryTags: ["meat"],
    difficulty: "hard",
    nutrition: { calories: 475, protein: 22, carbs: 28, fat: 32 },
    servings: 4,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 25,
    name: "Dummy Feijoada",
    cuisine: "Brazilian",
    dietaryTags: ["meat"],
    difficulty: "hard",
    nutrition: { calories: 480, protein: 28, carbs: 38, fat: 22 },
    servings: 5,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 26,
    name: "Dummy Kimchi Stew",
    cuisine: "Korean",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 210, protein: 7, carbs: 22, fat: 8 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 27,
    name: "Dummy Samosa",
    cuisine: "Indian",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 130, protein: 4, carbs: 17, fat: 5 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 28,
    name: "Dummy Empanada",
    cuisine: "Spanish",
    dietaryTags: ["meat"],
    difficulty: "easy",
    nutrition: { calories: 180, protein: 6, carbs: 20, fat: 8 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 29,
    name: "Dummy Tagine",
    cuisine: "Moroccan",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 390, protein: 16, carbs: 35, fat: 17 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 30,
    name: "Dummy Fettuccine Alfredo",
    cuisine: "Italian",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 400, protein: 13, carbs: 52, fat: 15 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 31,
    name: "Dummy Chow Mein",
    cuisine: "Chinese",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 350, protein: 14, carbs: 48, fat: 10 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 32,
    name: "Dummy Dolma",
    cuisine: "Turkish",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 105, protein: 4, carbs: 18, fat: 3 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 33,
    name: "Dummy Pierogi",
    cuisine: "Polish",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 160, protein: 5, carbs: 24, fat: 5 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 34,
    name: "Dummy Tabbouleh",
    cuisine: "Lebanese",
    dietaryTags: ["vegan"],
    difficulty: "easy",
    nutrition: { calories: 90, protein: 2, carbs: 18, fat: 2 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 35,
    name: "Dummy Okonomiyaki",
    cuisine: "Japanese",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 280, protein: 7, carbs: 40, fat: 11 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 36,
    name: "Dummy Arepas",
    cuisine: "Venezuelan",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 220, protein: 5, carbs: 40, fat: 4 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 37,
    name: "Dummy Malai Kofta",
    cuisine: "Indian",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 370, protein: 10, carbs: 35, fat: 19 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 38,
    name: "Dummy Poutine",
    cuisine: "Canadian",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 490, protein: 12, carbs: 52, fat: 25 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 39,
    name: "Dummy Baklava",
    cuisine: "Turkish",
    dietaryTags: ["vegetarian"],
    difficulty: "hard",
    nutrition: { calories: 320, protein: 5, carbs: 38, fat: 17 },
    servings: 6,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 40,
    name: "Dummy Rendang",
    cuisine: "Indonesian",
    dietaryTags: ["meat"],
    difficulty: "hard",
    nutrition: { calories: 570, protein: 27, carbs: 20, fat: 40 },
    servings: 4,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 41,
    name: "Dummy Hummus",
    cuisine: "Middle Eastern",
    dietaryTags: ["vegan"],
    difficulty: "easy",
    nutrition: { calories: 120, protein: 4, carbs: 13, fat: 6 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 42,
    name: "Dummy Gyoza",
    cuisine: "Japanese",
    dietaryTags: ["meat"],
    difficulty: "easy",
    nutrition: { calories: 190, protein: 7, carbs: 21, fat: 7 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 43,
    name: "Dummy Quiche",
    cuisine: "French",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 280, protein: 9, carbs: 22, fat: 17 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 44,
    name: "Dummy Chowder",
    cuisine: "American",
    dietaryTags: ["seafood"],
    difficulty: "medium",
    nutrition: { calories: 260, protein: 8, carbs: 27, fat: 11 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 45,
    name: "Dummy Enchiladas",
    cuisine: "Mexican",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 340, protein: 14, carbs: 36, fat: 14 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 46,
    name: "Dummy Lasagna",
    cuisine: "Italian",
    dietaryTags: ["vegetarian"],
    difficulty: "medium",
    nutrition: { calories: 380, protein: 16, carbs: 45, fat: 16 },
    servings: 4,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 47,
    name: "Dummy Tamales",
    cuisine: "Mexican",
    dietaryTags: ["meat"],
    difficulty: "hard",
    nutrition: { calories: 270, protein: 10, carbs: 28, fat: 12 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 48,
    name: "Dummy Polenta",
    cuisine: "Italian",
    dietaryTags: ["vegetarian"],
    difficulty: "easy",
    nutrition: { calories: 130, protein: 4, carbs: 28, fat: 2 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 49,
    name: "Dummy Cacciatore",
    cuisine: "Italian",
    dietaryTags: ["meat"],
    difficulty: "medium",
    nutrition: { calories: 340, protein: 18, carbs: 22, fat: 15 },
    servings: 3,
    image: "https://placehold.jp/150x150.png",
  },
  {
    id: 50,
    name: "Dummy Fajitas",
    cuisine: "Mexican",
    dietaryTags: ["meat"],
    difficulty: "easy",
    nutrition: { calories: 300, protein: 12, carbs: 35, fat: 10 },
    servings: 2,
    image: "https://placehold.jp/150x150.png",
  },
];