version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot
    env_file:
      - ./backend/.env.local
    working_dir: /home/app
    command: ["sh", "-c", "./mvnw spring-boot:run"]
    volumes:
      - ./backend:/home/app
      - ~/.m2:/root/.m2
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgresql
    env_file:
      - ./db/.env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  frontend_node_modules:
  pgdata: