/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Test API Project
 * Test API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const authControllerGetHello = <TData = AxiosResponse<null>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/auth/hello`,options
    ).then((res) => {if (res.data === "") res.data = null; return res as TData;});
  }

export const authControllerLogin = <TData = AxiosResponse<null>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,undefined,options
    ).then((res) => {if (res.data === "") res.data = null; return res as TData;});
  }

export type AuthControllerGetHelloResult = AxiosResponse<null>
export type AuthControllerLoginResult = AxiosResponse<null>
