name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**' 
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy job"
# Todo: Backend CI/CDの実装